<?php
if (!defined('TYPO3_MODE')) {
    die ('Access denied.');
}

return array(
    'ctrl' => array(
        'title' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations',
        'label' => 'type',
        // this call is for list view
        'label_userFunc' => 'Digicademy\Academy\Utility\Backend\LabelUtility->relationsLabel',
        // and this call for the IRRE table headers (necessary from 7.6+)
        'formattedLabel_userFunc' => 'Digicademy\Academy\Utility\Backend\LabelUtility->relationsLabel',
        'default_sortby' => 'ORDER BY type',
        'type' => 'type',
        'tstamp' => 'tstamp',
        'crdate' => 'crdate',
        'dividers2tabs' => 0,
        'versioningWS' => 2,
        'versioning_followPages' => true,
        'origUid' => 't3_origuid',
        'languageField' => 'sys_language_uid',
        'transOrigPointerField' => 'l10n_parent',
        'transOrigDiffSourceField' => 'l10n_diffsource',
        'delete' => 'deleted',
        'enablecolumns' => array(
            'disabled' => 'hidden',
            'starttime' => 'starttime',
            'endtime' => 'endtime',
        ),
        'iconfile' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('academy') . 'Resources/Public/Icons/tx_academy_domain_model_relations.svg'
    ),
    'interface' => array(
        'showRecordFieldList' => '
            sys_language_uid, 
            l10n_parent, 
            l10n_diffsource, 
            hidden, 
            type, 
            persistent_identifier,
            role, 
            role_freetext,
            date_range,
            project, 
            project_symmetric,
            event,
            event_symmetric, 
            person, 
            person_symmetric,
            medium,
            medium_symmetric, 
            news,
            news_symmetric, 
            unit, 
            unit_symmetric,
            product, 
            product_symmetric,
            service, 
            service_symmetric,
            publication, 
            publication_symmetric,
            hcard, 
            freetext, 
            sorting,
            sorting_symmetric,
        ',
    ),
    'types' => array(

        '0' => array('showitem' => 'type'),

        '10' => array('showitem' => 'type,person,hcard,date_range'),
        '11' => array('showitem' => 'type,role,role_freetext,person,project,date_range,freetext'),
        '12' => array('showitem' => 'type,role,role_freetext,person,unit,date_range,freetext'),
        '13' => array('showitem' => 'type,role,role_freetext,person,event,date_range,freetext'),
        '14' => array('showitem' => 'type,role,role_freetext,person,news,date_range,freetext'),
        '15' => array('showitem' => 'type,role,role_freetext,person,medium,date_range,freetext'),
        '16' => array('showitem' => 'type,role,role_freetext,person,person_symmetric,date_range,freetext'),

        '20' => array('showitem' => 'type,role,role_freetext,project,hcard,date_range'),
        '21' => array('showitem' => 'type,role,role_freetext,project,unit,date_range,freetext'),
        '22' => array('showitem' => 'type,role,role_freetext,project,news,date_range,freetext'),
        '23' => array('showitem' => 'type,role,role_freetext,project,event,date_range,freetext'),
        '24' => array('showitem' => 'type,role,role_freetext,project,medium,date_range,freetext'),
        '25' => array('showitem' => 'type,role_freetext,project,freetext,date_range'),
        '26' => array('showitem' => 'type,role,role_freetext,project,project_symmetric,date_range,freetext'),

        '30' => array('showitem' => 'type,unit,hcard,date_range'),
        '31' => array('showitem' => 'type,role,role_freetext,unit,freetext,date_range'),
        '32' => array('showitem' => 'type,role,unit,unit_symmetric,date_range,freetext'),
        '33' => array('showitem' => 'type,role,unit,news,date_range,freetext'),
        '34' => array('showitem' => 'type,role,unit,event,date_range,freetext'),
        '35' => array('showitem' => 'type,role,unit,medium,date_range,freetext'),

        '40' => array('showitem' => 'type,news,hcard,date_range'),
        '41' => array('showitem' => 'type,news,event,date_range,freetext'),
        '42' => array('showitem' => 'type,news,medium,date_range,freetext'),
        '43' => array('showitem' => 'type,news,news_symmetric,date_range,freetext'),

        '50' => array('showitem' => 'type,event,hcard,date_range'),
        '51' => array('showitem' => 'type,event,medium,date_range,freetext'),
        '52' => array('showitem' => 'type,event,event_symmetric,date_range,freetext'),

        '60' => array('showitem' => 'type,medium,medium_symmetric,date_range,freetext'),

        '70' => array('showitem' => 'type,role,role_freetext,person,product,date_range,freetext'),
        '71' => array('showitem' => 'type,role,role_freetext,project,product,date_range,freetext'),
        '72' => array('showitem' => 'type,role,role_freetext,unit,product,date_range,freetext'),
        '73' => array('showitem' => 'type,role,role_freetext,medium,product,date_range,freetext'),
        '74' => array('showitem' => 'type,role,role_freetext,news,product,date_range,freetext'),
        '75' => array('showitem' => 'type,role,role_freetext,event,product,date_range,freetext'),
        '76' => array('showitem' => 'type,role,role_freetext,service,product,date_range,freetext'),
        '77' => array('showitem' => 'type,role,role_freetext,publication,product,date_range,freetext'),
        '78' => array('showitem' => 'type,role,role_freetext,product,product_symmetric,date_range,freetext'),

        '80' => array('showitem' => 'type,role,role_freetext,person,service,date_range,freetext'),
        '81' => array('showitem' => 'type,role,role_freetext,project,service,date_range,freetext'),
        '82' => array('showitem' => 'type,role,role_freetext,unit,service,date_range,freetext'),
        '83' => array('showitem' => 'type,role,role_freetext,medium,service,date_range,freetext'),
        '84' => array('showitem' => 'type,role,role_freetext,news,service,date_range,freetext'),
        '85' => array('showitem' => 'type,role,role_freetext,event,service,date_range,freetext'),
        '86' => array('showitem' => 'type,role,role_freetext,publication,service,date_range,freetext'),
        '87' => array('showitem' => 'type,role,role_freetext,service,service_symmetric,date_range,freetext'),

        '90' => array('showitem' => 'type,role,role_freetext,person,publication,date_range,freetext'),
        '91' => array('showitem' => 'type,role,role_freetext,project,publication,date_range,freetext'),
        '92' => array('showitem' => 'type,role,role_freetext,unit,publication,date_range,freetext'),
        '93' => array('showitem' => 'type,role,role_freetext,medium,publication,date_range,freetext'),
        '94' => array('showitem' => 'type,role,role_freetext,news,publication,date_range,freetext'),
        '95' => array('showitem' => 'type,role,role_freetext,event,publication,date_range,freetext'),
        '96' => array('showitem' => 'type,role,role_freetext,publication,publication_symmetric,date_range,freetext'),
    ),
    'palettes' => array(
        '1' => array('showitem' => ''),
    ),
    'columns' => array(
        'sys_language_uid' => [
            'exclude' => true,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.language',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'special' => 'languages',
                'items' => [
                    [
                        'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.allLanguages',
                        -1,
                        'flags-multiple'
                    ],
                ],
                'default' => 0,
            ]
        ],
        'l10n_parent' => [
            'displayCond' => 'FIELD:sys_language_uid:>:0',
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.l10n_parent',
            'config' => [
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_relations',
                'size' => 1,
                'maxitems' => 1,
                'minitems' => 0,
                'default' => 0,
            ],
        ],
        'l10n_diffsource' => array(
            'config' => array(
                'type' => 'passthrough',
            ),
        ),
        't3ver_label' => array(
            'label' => 'LLL:EXT:lang/locallang_general.xml:LGL.versionLabel',
            'config' => array(
                'type' => 'input',
                'size' => '30',
                'max' => '255',
            )
        ),
        'hidden' => array(
            'exclude' => 1,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.hidden',
            'config' => array(
                'type' => 'check',
            ),
        ),
        'starttime' => array(
            'exclude' => 1,
            'l10n_mode' => 'mergeIfNotBlank',
            'label' => 'LLL:EXT:lang/locallang_general.php:LGL.starttime',
            'config' => array(
                'type' => 'input',
                'size' => '10',
                'max' => '20',
                'eval' => 'datetime',
                'checkbox' => '0',
                'default' => '0',
            ),
        ),
        'endtime' => array(
            'exclude' => 1,
            'l10n_mode' => 'mergeIfNotBlank',
            'label' => 'LLL:EXT:lang/locallang_general.php:LGL.endtime',
            'config' => array(
                'type' => 'input',
                'size' => '8',
                'max' => '20',
                'eval' => 'datetime',
                'checkbox' => '0',
                'default' => '0',
                'range' => array(
                    'upper' => mktime(0, 0, 0, 12, 31, date('Y') + 10),
                    'lower' => mktime(0, 0, 0, date('m') - 1, date('d'), date('Y'))
                ),
            ),
        ),
        'persistent_identifier' => array(
            'config' => array(
                'type' => 'passthrough',
            ),
        ),
        'sorting' => array(
            'config' => array(
                'type' => 'passthrough',
            ),
        ),
        'sorting_symmetric' => array(
            'config' => array(
                'type' => 'passthrough',
            ),
        ),
        'type' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.type',
            'l10n_mode' => 'exclude',
            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'select',
                'renderType' => 'selectSingle',
                'size' => 1,
                'minitems' => 1,
                'maxitems' => 1,
                'eval' => 'required',
            ),
        ),
        'role' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.role',
            'l10n_mode' => 'exclude',
            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'select',
                'renderType' => 'selectSingle',
                'foreign_table' => 'tx_academy_domain_model_roles',
                'foreign_table_where' => 'AND tx_academy_domain_model_roles.sys_language_uid IN (-1,###REC_FIELD_sys_language_uid###) ORDER BY tx_academy_domain_model_roles.title',
                'items' => array(
                    array('', 0),
                ),
                'minitems' => 0,
                'maxitems' => 1,
            ),
        ),
        'role_freetext' => array(
            'exclude' => 1,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.role_freetext',
            'config' => array(
                'type' => 'input',
                'size' => 20,
                'eval' => 'trim'
            ),
        ),
        'date_range' => array(
            'exclude' => 1,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xlf:tx_academy_domain_model_relations.date_range',
            'l10n_mode' => 'exclude',
            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'inline',
                'foreign_table' => 'tx_chftime_domain_model_dateranges',
                'foreign_field' => 'parent',
                'foreign_table_field' => 'tablename',
                'minitems' => 0,
                'maxitems' => 1,
                'behaviour' => array(
                    'disableMovingChildrenWithParent' => 1,
                ),
                'appearance' => array(
                    'collapseAll' => 1,
                    'expandSingle' => 1,
                    'newRecordLinkAddTitle' => 1,
                    'newRecordLinkPosition' => 'bottom',
                    'levelLinksPosition' => 'bottom',
                ),
            ),
        ),
        'project' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.project',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_projects',
                'foreign_table' => 'tx_academy_domain_model_projects',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'project_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.project',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_projects',
                'foreign_table' => 'tx_academy_domain_model_projects',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'event' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.event',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_news_domain_model_news',
                'foreign_table' => 'tx_news_domain_model_news',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'event_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.event',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_news_domain_model_news',
                'foreign_table' => 'tx_news_domain_model_news',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'person' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.person',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_persons',
                'foreign_table' => 'tx_academy_domain_model_persons',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'person_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.person',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_persons',
                'foreign_table' => 'tx_academy_domain_model_persons',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'medium' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.medium',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_media',
                'foreign_table' => 'tx_academy_domain_model_media',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'medium_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.medium',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_media',
                'foreign_table' => 'tx_academy_domain_model_media',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'news' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.news',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_news_domain_model_news',
                'foreign_table' => 'tx_news_domain_model_news',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'news_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.news',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_news_domain_model_news',
                'foreign_table' => 'tx_news_domain_model_news',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'unit' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.unit',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_units',
                'foreign_table' => 'tx_academy_domain_model_units',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'unit_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.unit',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_units',
                'foreign_table' => 'tx_academy_domain_model_units',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'product' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.product',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_products',
                'foreign_table' => 'tx_academy_domain_model_products',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'product_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.product_symmetric',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_products',
                'foreign_table' => 'tx_academy_domain_model_products',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'service' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.service',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_services',
                'foreign_table' => 'tx_academy_domain_model_services',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'service_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.service_symmetric',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_services',
                'foreign_table' => 'tx_academy_domain_model_services',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'publication' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.publication',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_publications',
                'foreign_table' => 'tx_academy_domain_model_publications',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'publication_symmetric' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.publication_symmetric',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_publications',
                'foreign_table' => 'tx_academy_domain_model_publications',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'hcard' => array(
            'exclude' => 0,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.hcard',
//            'l10n_mode' => 'exclude',
//            'l10n_display' => 'defaultAsReadonly',
            'config' => array(
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => 'tx_academy_domain_model_hcards',
                'foreign_table' => 'tx_academy_domain_model_hcards',
                'maxitems' => 1,
                'size' => 1,
                'behaviour' => [
                    'allowLanguageSynchronization' => true,
                ],
            ),
        ),
        'freetext' => array(
            'exclude' => 1,
            'label' => 'LLL:EXT:academy/Resources/Private/Language/locallang_db.xml:tx_academy_domain_model_relations.freetext',
            'config' => array(
                'type' => 'text',
                'cols' => 40,
                'rows' => 10,
                'eval' => 'trim',
                'default' => '',
            ),
        ),
    ),
);
