services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Digicademy\Academy\:
    resource: '../Classes/*'

  # We need the to inject the container instance for some dependency fetching,
  # so we need to autowire the container itself.
  TYPO3\CMS\Extbase\Object\Container\Container:

  GeorgRinger\News\Domain\Model\News: '@Digicademy\Academy\Domain\Model\News'
  GeorgRinger\Eventnews\Domain\Model\News: '@Digicademy\Academy\Domain\Model\Events'
